version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/"
    ports:
      - "127.0.0.1:5433:5432"