version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/"
    ports:
      - "127.0.0.1:5433:5432"
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lk_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db


volumes:
  postgres_data: